using System;using System.IO;using System.Text;using UnityEngine;using UnityEditor;using LastSignal;
internal class CommandScript:IRunCommand{public void Execute(ExecutionResult r){S014MovementLive.Begin();r.Log("Movement/door canlı kayıt başladı.");}}
internal static class S014MovementLive{
static SessionFlow flow;static GameObject player;static FirstPersonLook look;static FirstPersonMotor motor;static PlayerInputReader input;static DoorInteractable door;static double start,last,next;static int frame,phase;static string dir;static StringBuilder log=new StringBuilder();static double[] times={0,4,8,9,12,15,18,21,24,27,30,33};
public static void Begin(){flow=UnityEngine.Object.FindAnyObjectByType<SessionFlow>();flow.ReturnToMenu();flow.BeginSession();flow.Resume();player=flow.Player;look=player.GetComponent<FirstPersonLook>();motor=player.GetComponent<FirstPersonMotor>();input=player.GetComponent<PlayerInputReader>();input.FocusLost-=flow.Pause;foreach(var z in UnityEngine.Object.FindObjectsByType<ZombieController>())z.SetPaused(true);motor.enabled=false;door=UnityEngine.Object.FindAnyObjectByType<DoorInteractable>();Place(new Vector3(-300,.08f,-100),Vector3.forward);dir=File.ReadAllText("/tmp/s014-movement-live-run").Trim();Directory.CreateDirectory(dir+"/frames");log.AppendLine("frame,realtime,phase,x,y,z,pitch,fov,door_open,door_busy,door_obstructed");start=last=EditorApplication.timeSinceStartup;EditorApplication.update+=Tick;}
static void Place(Vector3 p,Vector3 f){var cc=player.GetComponent<CharacterController>();cc.enabled=false;player.transform.position=p;player.transform.rotation=Quaternion.LookRotation(f);cc.enabled=true;Physics.SyncTransforms();}
static void Fov(float value){var s=new SerializedObject(look);s.FindProperty("fieldOfViewDegrees").floatValue=value;s.ApplyModifiedPropertiesWithoutUndo();}
static void Tick(){try{double now=EditorApplication.timeSinceStartup,t=now-start;float dt=(float)Math.Min(now-last,.05);last=now;if(phase<times.Length&&t>=times[phase])Act(phase++);if(t<12)motor.Simulate(Vector2.up,t>=4,dt);else if(t<15)motor.Simulate(Vector2.up,false,dt);if(t>=36){Finish("CAPTURED — public motor/door commands; controlled positioning; not D140");return;}if(t<next)return;next=t+1.0/12;ScreenCapture.CaptureScreenshot(dir+"/frames/"+frame.ToString("D5")+".png");var p=player.transform.position;log.AppendLine(FormattableString.Invariant($"{frame},{t:F6},{phase},{p.x},{p.y},{p.z},{look.Pitch},{look.View.fieldOfView},{door.IsOpen},{door.Busy},{door.Obstructed}"));frame++;}catch(Exception e){Finish("FAIL "+e);}}
static void Act(int n){switch(n){case 0:Fov(60);break;case 1:Fov(75);break;case 2:Fov(100);break;case 3:if(!motor.TryStartSlide())throw new Exception("Slide request rejected");break;case 4:player.GetComponent<PlayerStance>().TrySetCrouching(true);break;case 5:player.GetComponent<PlayerStance>().TrySetCrouching(false);break;case 6:look.ApplyRecoil(-85-look.Pitch,0);break;case 7:look.ApplyRecoil(85-look.Pitch,0);break;case 8:look.ApplyRecoil(-look.Pitch,0);Fov(75);Place(door.transform.position+new Vector3(0,0,-3),Vector3.forward);if(!door.TryInteract())throw new Exception("Door open rejected");break;case 9:if(!door.IsOpen||door.Busy)throw new Exception("Door did not finish opening");if(!door.TryInteract())throw new Exception("Door close rejected");break;case 10:if(door.IsOpen||door.Busy)throw new Exception("Door did not finish closing");break;case 11:player.GetComponent<PlayerCombatController>().SelectSlot(PlayerCombatController.CombatSlot.Melee);break;}}
static void Finish(string s){EditorApplication.update-=Tick;File.WriteAllText(dir+"/timeline.csv",log.ToString());File.WriteAllText(dir+"/result.txt",s);if(input&&flow)input.FocusLost+=flow.Pause;if(flow)flow.Pause();}
}
