using System;using System.IO;using System.Text;using UnityEngine;using UnityEditor;using LastSignal;using LastSignal.Slice;
internal class CommandScript:IRunCommand{public void Execute(ExecutionResult result){ S014ZombieLive.Begin();result.Log("Canlı production zombie capture başladı; kontrollü fixture, final D140 değil.");}}
internal static class S014ZombieLive{
static SessionFlow flow;static S014PopulationCapture fixture;static ZombieController actor;static FirstPersonLook look;static PlayerInputReader input;static PlayerCombatController combat;static double start,next;static int frame,phase;static string dir;static readonly StringBuilder log=new StringBuilder();static readonly double[] times={0,12,15,19,23,26,30,33,37,40};
public static void Begin(){flow=UnityEngine.Object.FindAnyObjectByType<SessionFlow>();flow.Resume();fixture=new GameObject("S014 visual fixture").AddComponent<S014PopulationCapture>();fixture.PrepareFixture(flow,1);actor=fixture.ActiveActors[0];look=flow.Player.GetComponent<FirstPersonLook>();look.enabled=true;input=flow.Player.GetComponent<PlayerInputReader>();input.FocusLost-=flow.Pause;combat=flow.Player.GetComponent<PlayerCombatController>();dir=File.ReadAllText("/tmp/lastsignal-s014-zombie-live-run").Trim();Directory.CreateDirectory(dir+"/frames");start=EditorApplication.timeSinceStartup;log.AppendLine("frame,realtime,phase,zombie_state,attack_sequence,attack_time,contacts,melee_result,zombie_health,melee_weapon_result");EditorApplication.update+=Tick;}
static void Aim(){var d=actor.transform.position+Vector3.up*1.2f-look.View.transform.position;flow.Player.transform.rotation=Quaternion.LookRotation(Vector3.ProjectOnPlane(d,Vector3.up));look.ApplyRecoil(Mathf.Atan2(-d.y,new Vector2(d.x,d.z).magnitude)*Mathf.Rad2Deg-look.Pitch,0);}
static void Place(Vector3 offset){var cc=flow.Player.GetComponent<CharacterController>();cc.enabled=false;flow.Player.transform.position=actor.transform.position+offset+Vector3.up*.05f;cc.enabled=true;Physics.SyncTransforms();Aim();}
static void Tick(){try{double t=EditorApplication.timeSinceStartup-start;if(!EditorApplication.isPlaying||!actor){Finish("ABORTED");return;}if(phase<times.Length&&t>=times[phase]){Act(phase++);}if(t>=43){Finish("CAPTURED — controlled live production actor; visual review required");return;}if(t<next)return;next=t+1.0/15;ScreenCapture.CaptureScreenshot(dir+"/frames/"+frame.ToString("D5")+".png");log.AppendLine(FormattableString.Invariant($"{frame},{t:F6},{phase},{actor.Runtime.State},{actor.AttackSequence},{actor.AttackTime},{actor.ContactAttempts},{actor.LastMeleeResult},{actor.GetComponent<ZombieHealth>().CurrentHealth},{combat.Melee.LastMeleeResult}"));frame++;}catch(Exception e){Finish("FAIL "+e);}}
static void Act(int p){switch(p){case 0:Aim();break;case 1:Place(Vector3.right*4);break;case 2:Place(Vector3.forward*5);break;case 3:combat.SelectSlot(PlayerCombatController.CombatSlot.Melee);Place(actor.transform.forward*1.2f);combat.Melee.TryAttack();break;case 4:Place(actor.transform.forward*4);combat.Melee.TryAttack();break;case 5:Place(actor.transform.forward*1.2f);combat.Melee.TryAttack();break;case 6:combat.SelectSlot(PlayerCombatController.CombatSlot.Firearm);Aim();combat.Firearm.OnFirePressed();combat.Firearm.OnFireReleased();break;case 7:actor.GetComponent<ZombieHealth>().TakeDamage(new DamageInfo{Amount=500,Category=DamageCategory.Bullet,BodyPart=ZombieBodyPart.Head,Region=DamageRegion.Head,Direction=look.View.transform.forward,SourcePosition=look.View.transform.position,HitPoint=actor.transform.position+Vector3.up*1.7f,Instigator=flow.Player});break;case 8:Place(Vector3.right*2);break;case 9:Place(Vector3.back*2);break;}}
static void Finish(string result){EditorApplication.update-=Tick;File.WriteAllText(dir+"/timeline.csv",log.ToString());File.WriteAllText(dir+"/result.txt",result);if(input&&flow)input.FocusLost+=flow.Pause;if(fixture)UnityEngine.Object.Destroy(fixture.gameObject);if(flow)flow.Pause();}
}
